# Generated by Django 3.2.2 on 2021-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
